### ISSUE TITLE
About "insert graph"

### ISSUE THREAD

**Issue by lh3** [thegenemyers/GFA-spec#2]
This post is related to pmelsted/GFA-spec#33, but to avoid distraction, I will raise it here. The following does not solve issues. It just gives an observation, which may or may not be useful.

What grabs my attention is this figure in your proposal:

![](https://raw.githubusercontent.com/thegenemyers/GFA-spec/master/GFA2.Fig2.png)
If we only consider 0-length overlaps for now, the "After" graph is @richarddurbin's _insert graph_. An insert graph only has one operation, _insert_:

```
I  <sid0>  <sid1>:<pos1>:<ori1>  <sid2>:<pos2>:<ori2>
```

Briefly, the 5'-end of `<sid0>` is inserted to a position on `<sid1>` and 3'-end to `<sid2>`, both with orientations. The "After" graph can be written as (again, assuming 0-length overlaps):

```
I  short1  long:100:+  long:110:+
I  short2  long:300:+  long:320:+
```

Generally, if we start from any "Before" graph consisting of 0-length dovetails, the "After" graph can always be represented by an insert graph. This is because: (1) any dovetail graph can be represented by an insert graph and (2) merging any dovetail overlaps, including merging at branching points, still yields an insert graph. When there are overlaps, we may allow overlap lengths in an insert operation.

Perhaps insert graph is a natural way to describe variants in an assembly?

**Comment by thegenemyers** [comment]
Inserts are insufficient when the overlaps are not 0-length.  Without E I cannot express the set of all relationships found by daligner, etc.  The generality of E is precisely what is interesting about it and why it is useful.

**Comment by lh3** [comment]
Thanks a lot for the explanation. I am closing this issue now.
